// Code generated by go-swagger; DO NOT EDIT.

package base

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Base implementation\n",
    "title": "Base",
    "version": "0.1.0"
  },
  "host": "0.0.0.0:8080",
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "description": "Index",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "index"
        ],
        "summary": "Index",
        "operationId": "Index",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PingResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "PingResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/ResponseMeta"
        }
      ]
    },
    "ResponseMeta": {
      "type": "object",
      "properties": {
        "meta": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Base implementation\n",
    "title": "Base",
    "version": "0.1.0"
  },
  "host": "0.0.0.0:8080",
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "description": "Index",
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "index"
        ],
        "summary": "Index",
        "operationId": "Index",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PingResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "PingResponse": {
      "allOf": [
        {
          "$ref": "#/definitions/ResponseMeta"
        }
      ]
    },
    "ResponseMeta": {
      "type": "object",
      "properties": {
        "meta": {
          "type": "string"
        }
      }
    }
  }
}`))
}
