// Code generated by go-swagger; DO NOT EDIT.

// Package base_extra Base
//
//  Base implementation
//
//  Schemes:
//    http
//    https
//  Host: 0.0.0.0:8080
//  BasePath: /
//  Version: 0.1.0
//
//  Consumes:
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - application/json
//
// swagger:meta
package base_extra
