swagger: '2.0'
info:
  description: |
    Base implementation
  title: Base
  version: 0.1.0
host: '0.0.0.0:8080'
basePath: /
schemes:
  - http
  - https
paths:
  "/":
    get:
      consumes:
        - application/x-www-form-urlencoded
      deprecated: false
      description: Index
      operationId: Index
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PingResponse'
      summary: Index
      tags:
        - index
definitions:
  ResponseMeta:
    properties:
      meta:
        type: string
    type: object
  PingResponse:
    allOf:
      - $ref: '#/definitions/ResponseMeta'


