// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PingResponse ping response
//
// swagger:model PingResponse
type PingResponse struct {
	ResponseMeta
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *PingResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ResponseMeta
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ResponseMeta = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m PingResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ResponseMeta)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this ping response
func (m *PingResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ResponseMeta
	if err := m.ResponseMeta.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this ping response based on the context it is used
func (m *PingResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ResponseMeta
	if err := m.ResponseMeta.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PingResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PingResponse) UnmarshalBinary(b []byte) error {
	var res PingResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
