// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TestResponse test response
//
// swagger:model TestResponse
type TestResponse struct {
	ResponseMeta

	// id
	ID string `json:"id,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TestResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 ResponseMeta
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.ResponseMeta = aO0

	// now for regular properties
	var propsTestResponse struct {
		ID string `json:"id,omitempty"`
	}
	if err := swag.ReadJSON(raw, &propsTestResponse); err != nil {
		return err
	}
	m.ID = propsTestResponse.ID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TestResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.ResponseMeta)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	// now for regular properties
	var propsTestResponse struct {
		ID string `json:"id,omitempty"`
	}
	propsTestResponse.ID = m.ID

	jsonDataPropsTestResponse, errTestResponse := swag.WriteJSON(propsTestResponse)
	if errTestResponse != nil {
		return nil, errTestResponse
	}
	_parts = append(_parts, jsonDataPropsTestResponse)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this test response
func (m *TestResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ResponseMeta
	if err := m.ResponseMeta.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this test response based on the context it is used
func (m *TestResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with ResponseMeta
	if err := m.ResponseMeta.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *TestResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TestResponse) UnmarshalBinary(b []byte) error {
	var res TestResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
